services:
  - type: static
    name: black-fingerprint
    buildCommand: ""
    staticPublishPath: ./
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
